### ISSUE TITLE
Can't trace

### ISSUE THREAD

**Issue by alijaya** [TomByrne/composure#1]
When I include your library... the trace text is not shown in swf. I use Hello World example btw.

**Comment by alijaya** [comment]
I think it's flash problem only... i test to compile to Neko, it's fine...

**Comment by TomByrne** [comment]
What IDE are you using?
It works fine for me (i.e. it prints thee trace into the trace TextField, as is default in haxe).
I have committed the HelloWorld.hx to the testSrc\org\tbyrne\composureTest directory.
Also, the FlashDevelop project (in 'FD Project' directory) is set up to run it.

Let me know if you're still having problems.

**Comment by alijaya** [comment]
I use Sublime Text 2, but I compiled it with terminal...

I try your HelloWorld code... but I have no luck, it didn't display anything...
I compiled with your latest code...
I compiled it like this
haxe -main org.tbyrne.composureTest.HelloWorld -swf9 output.swf -cp ../src -lib hsl-1

I open the file with Flash Player 10

**Comment by TomByrne** [comment]
That worked for me, I had to add the '-cp ../testSrc' so it could find the HelloWorld class.
What version of haxe are you compiling with?
Also, just be careful when updating, I've refactored the package 'org.tbyrne.composure' to just 'composure' today.

**Comment by alijaya** [comment]
hmmm it's weird... I use haxe 2.09 to compile this...

**Comment by TomByrne** [comment]
Yeah, that's what I'm using.
I'm not sure if this makes a difference, but have you got the debug player installed?

**Comment by alijaya** [comment]
yeah... I got debug player (the standalone player) version (10,0,42,34), and browser plugin (11,3,300,265), neither the players work.

Ah... I get the player works... It because the haxe version... I think I use the haxe nightbuild so it didn't work as expected. So I update the haxe, and it works as expected.

Thanks for your help :).
