### ISSUE TITLE
haxe.ds.GenericStack not found

### ISSUE THREAD

**Issue by Kamek** [TomByrne/composure#3]
When trying to compile my nme project using composure-hx I get this error:

```
    nme build linux

    /usr/lib/haxe/lib/composure-hx/2,0/org/tbyrne/collections/UniqueList.hx:2: characters 0-28        : Class not found : haxe.ds.GenericStack
```

Where can I find the GenericStack<T> class?

Haxe 2.10, Linux 3.7.10 i686, composure-hx 2.0, NME 3.5.5, hxcpp 3.0,  gcc 4.7.2, clang 3.2

**Comment by TomByrne** [comment]
That's a haxe 3 class. You'll have to use version 1.x for haxe 2.

**Comment by Kamek** [comment]
Oh ok, I'll build 3.0 and use that then thanks.
