### ISSUE TITLE
Promises not working in CPP target

### ISSUE THREAD

**Issue by isk** [TomByrne/composure#5]
Promise functions are not called in the CPP target, exact same code works fine in flash and neko (haven't tested others). Simple example of issue: https://gist.github.com/isk/28927db065a9c3bbb898

**Comment by TomByrne** [comment]
This works fine for me (using MSVS 2010 or MinGW).
What compiler are you using?
Are there any other macros/build tools in use?

**Comment by isk** [comment]
Ah sorry my bad, I just updated hxcpp and now it works.
